version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    target-branch: master
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    target-branch: master
